dist: bin
before:
  hooks:
    - go mod download
builds:
  - main: "./cmd/grafana-snapshot-helper.go"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}"
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - image_templates:
      - "whyeasy/{{ .ProjectName }}:latest"
      - "whyeasy/{{ .ProjectName }}:{{ .Tag }}"
checksum:
  name_template: "checksums.txt"
changelog:
  skip: false
