name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u whyeasy --password-stdin
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "whyeasy/grafana-snapshot-helper:${{ github.ref }}"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
